### Torsion-Resistant Handed-Shearing Auxetics (HSA)-based Soft Gripper

Soft robots excel where delicate manipulation and safe human-robot collaboration are vital. However, a lack of skeleton makes it unsuitable for most practical applications.
In this work, I addressed this problem by designing and integrating a torsion-resistant strain limiting layer (TR-SLL) to metamaterial-based soft grippers.
This reduces out-of-plane bending while maintaining the gripper's compliance and in-plane flexibility.

<div style="text-align: center; margin: 20px 0;">
<video width="70%" autoplay loop muted playsinline>
  <source src="projects/HSA-Gripper-Lifting.mp4" type="video/mp4">
</video>

*TR-SLL-integrated HSA Gripper lifting different objects from the YCB object dataset. This is a benchmark we test against, and the gripper achieved a successful rate of 86% when test with 43 objects.*

</div>


As a result, the use of our TR-SLL HSA gripper enabled grasping of payloads over 1 kg when pinched. It also helped us achieve a lifting
capacity of 5 kg when loading using the TR-SLL element. We were able to hit a peak pinch grasp force of 5.8 N and a peak planar caging force of 14.5 N, which is
a significant payload achieved by a soft gripper when lifting objects perpendicular to the gravity. Read more about this work [here](https://arxiv.org/abs/2412.07976){target="_blank"}

*This work was supported by the NSF, Murdock Charitable Trust, and the Office of Naval Research (ONR)*