project:
  type: website
  output-dir: docs

website:
  title: "Srivatsan Balaji - Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: publications.qmd
        text: Publications
      - href: photography.qmd
        text: Photography
      - href: contact.qmd
        text: Contact

format:
  html:
    theme: cosmo
    html-math-method: katex