project:
  type: website
  output-dir: docs

website:
  title: "Srivatsan Balaji"
  favicon: gripper.png
  navbar:
    left:
      - href: index.qmd
        text: About
      - href: research.qmd
        text: Research
      - href: publications.qmd
        text: Publications
      - href: mentoring.qmd
        text: Mentoring
      - href: life-outside-research.qmd
        text: Life Outside Work
      - href: contact.qmd
        text: Contact and Socials

resources:
  - cv/

format:
  html:
    theme:
      light: [flatly, custom-light.scss]
      dark: [darkly, custom-dark.scss]
    css: styles.css
    html-math-method: katex
    include-in-header:
      text: |
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css">
    grid:
      body-width: 1200px
      sidebar-width: 0px
      margin-width: 0px