project:
  type: website
  output-dir: docs

website:
  title: "Srivatsan Balaji"
  favicon: favicon.png
  page-footer:
    center: "Made with [Quarto](https://quarto.org) and [GitHub Pages](https://pages.github.com)"
  navbar:
    left:
      - href: index.qmd
        text: About
      - href: research.qmd
        text: Research
      - href: publications.qmd
        text: Publications
      - href: photography.qmd
        text: Photography
      - href: contact.qmd
        text: Contact and Socials

format:
  html:
    theme: [flatly, custom.scss]
    css: styles.css
    html-math-method: katex
    include-in-header:
      text: |
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
    grid:
      body-width: 1200px
      sidebar-width: 0px
      margin-width: 0px