project:
  type: website

website:
  title: "Srivatsan's Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: publications.qmd
        text: Publications
      - href: contact.qmd
        text: Contact

format:
  html:
    theme: cosmo
    html-math-method: katex